### ISSUE TITLE
トップページのデモ配信

### ISSUE THREAD

**Issue by kyohmizu** [Fufuhu/showk3s#3]
備忘録。
https://cloudnativedays.slack.com/archives/CBWSR1HDX/p1563634515082000?thread_ts=1563599116.003100&cid=CBWSR1HDX

**Comment by Fufuhu** [comment]
追加しました。
![image](https://user-images.githubusercontent.com/8606080/61589535-0f5b9a00-abe6-11e9-9a90-3ae0bfc44518.png)
